# Generated by Django 5.2.6 on 2025-09-14 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=50)),
                ('details', models.TextField()),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Error', 'Error')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.CharField(max_length=100)),
                ('destination_ip', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=50)),
                ('bytes', models.IntegerField()),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Anomalous', 'Anomalous'), ('Blocked', 'Blocked')], max_length=50)),
                ('severity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.CharField(max_length=100)),
                ('destination_ip', models.CharField(max_length=100)),
                ('threat_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('confidence', models.IntegerField()),
            ],
        ),
    ]
