# Generated by Django 5.0.4 on 2026-04-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_threshold', models.IntegerField(default=75)),
                ('threat_threshold', models.IntegerField(default=85)),
                ('auto_block_threshold', models.IntegerField(default=95)),
                ('email_notifications', models.BooleanField(default=True)),
                ('slack_notifications', models.BooleanField(default=False)),
                ('telegram_notifications', models.BooleanField(default=False)),
                ('email_address', models.CharField(default='admin@company.com', max_length=255)),
                ('slack_webhook', models.CharField(blank=True, max_length=500, null=True)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_refresh_interval', models.IntegerField(default=5)),
                ('log_retention_days', models.IntegerField(default=30)),
                ('max_concurrent_scans', models.IntegerField(default=10)),
                ('dark_mode', models.BooleanField(default=True)),
                ('show_tooltips', models.BooleanField(default=True)),
                ('compact_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
